http:
  routers:
    modelbazaar-http:
      rule: "PathPrefix(`/api`)"
      priority: 10
      service: "backend-service"
      middlewares:
        - "limit-request-body-size"

    frontend-http:
      rule: "PathPrefix(`/`)"
      priority: 1
      service: "frontend-service"

    keycloak-http:
      rule: "PathPrefix(`/keycloak`)"
      priority: 10
      service: "keycloak-service"

  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8000"

    frontend-service:
      loadBalancer:
        servers:
          - url: "http://localhost:3000"

    keycloak-service:
      loadBalancer:
        servers:
          - url: "http://localhost:8180"

  middlewares:
    limit-request-body-size:
      buffering:
        # For reference: https://doc.traefik.io/traefik/v2.0/middlewares/buffering/
        maxRequestBodyBytes: 524288000 # 500MB in bytes
        memRequestBodyBytes: 1048576 # 1MB in bytes
