export const MULTI_AFFIL = "oa_multi_affil";
export const FUNDER_EOC = "oa_funder_eoc";
export const PUBLISHER_EOC = "oa_publisher_eoc";    // isn't used   
export const COAUTHOR_EOC = "oa_coauthor_eoc";
export const COAUTHOR_AFFIL_EOC = "oa_coauthor_affiliation_eoc";
export const AUTHOR_AFFIL_EOC = "oa_author_affiliation_eoc";
export const ACK_EOC = "oa_acknowledgement_eoc";
export const FORMAL_RELATIONS = "formal_relations";
export const UNI_FACULTY_EOC = "uni_faculty_eoc";
export const DOJ_PRESS_RELEASES_EOC = "doj_press_release_eoc"