azure:
  branches:
    demo-aux-db:
      pull_credentials:
        password: t7wCsweR823Lr4N8oKbOAwDvCSTSfr/pgQ7A8DRBH3+ACRALGFHl
        username: prism-pull-demo-aux-db
      push_credentials:
        password: 6QdVgwrYixrSdd5IGB2YnSp6WIj1jXHpHVRajVTG6n+ACRAPgg9w
        username: prism-push-demo-aux-db
      version: 0.0.2
    prod:
      pull_credentials:
        password: YA5Rm8350UhKrEQaaqNjbGk2TfjN+ri7Cy0Di9UReB+ACRBRSYKs
        username: prism-pull
      push_credentials:
        password: QfKXji872oiQaHrp+ZgjfSs1ertCeInK+D0PBDXe4c+ACRCB3faT
        username: prism-push
      version: 0.0.3
  registry: prismresearchsecurity.azurecr.io
provider: azure
