azure:
  branches:
    kartik-ux:
      pull_credentials:
        password: RGaZZLuybLXtKgIJv0LBq9q+NKSQa6FpmicreUuZ12+ACRBrUaO9
        username: prism-pull-kartik-ux
      push_credentials:
        password: n8rjvLE4oGe7tauu0EAW1XeUV+kaQvslu9OATcSjJS+ACRBRCDEv
        username: prism-push-kartik-ux
      version: 0.0.1
    test-docker:
      pull_credentials:
        password: y3ATmxOBiPrHeQYqRLS4obJ2rn2RkNavlqAsKclu0H+ACRCPe12P
        username: prism-pull-test-docker
      push_credentials:
        password: woQh5tTYczBGMjDrU04DmKHNHx2WhCLQItTJ79ktDR+ACRCN9Ott
        username: prism-push-test-docker
      version: 0.0.10
  registry: prismresearchsecurity.azurecr.io
provider: azure
