# Uri for postgres db
postgres_uri: "postgresql://<username>:<password>@<host | localhost>:<port | 5432>/prism"
fundcode_triangulation_postgres_uri: ""

# Logfile for backend
logfile: "./worker.log"

# License for NDB
ndb_license: "license path or key"

# Work dir for worker, will store ndbs and caches etc.
work_dir: ""

# Path to load data to construct ndbs for author flaggers
ndb_data:
    university: ""
    doc: ""
    aux: ""

# Endpoint for grobid
grobid_endpoint: ""
