# Uri for postgres db
postgres_uri: "postgresql://<username>:<password>@<host | localhost>:<port | 5432>/prism"

# Logfile for backend
logfile: "./worker.log"

# License for Prism
prism_license: "license key"

# Work dir for worker, will store ndbs and caches etc.
work_dir: ""

# Path to load data to construct ndbs for author flaggers
ndb_data:
    university: ""
    doc: ""
    aux: ""

# Endpoint for grobid
grobid_endpoint: ""
