# Uri for postgres db
postgres_uri: ""

# Path to entity NDB
entity_ndb: ""

# Args for setting up keycloak
keycloak:
    keycloak_server_url: ""
    keycloak_admin_username: ""
    keycloak_admin_password: ""
    public_hostname: ""
    private_hostname: ""
    ssl_login: false
    verbose: false

# Port to run backend server on
port: 3000

# Logfile for backend
logfile: "./prism_backend.log"

# License for NDB
ndb_license: "license path or key"