# Uri for postgres db
postgres_uri: "postgresql://<username>:<password>@<host | localhost>:<port | 5432>/prism"

# Path to the searchable_entities.json that contains the entities that we can search
# in the match endpoint
searchable_entities: ""

# Args for setting up keycloak
keycloak:
    keycloak_server_url: ""
    keycloak_admin_username: ""
    keycloak_admin_password: ""
    public_hostname: ""
    private_hostname: ""
    ssl_login: false
    verbose: false

# Port to run backend server on
port: 8000

# Logfile for backend
logfile: "./prism_backend.log"

# License for Prism
prism_license: "license key"