name: Update Data and Create PR

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * 1" # Run every Monday at 12:00 UTC

jobs:
  update-data:
    runs-on: ubuntu-latest-8-cores

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "pratik@thirdai.com"

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Fetch branches
        run: |
          git fetch --all

      - name: Install dependencies
        run: |
          # python -m pip install --upgrade pip
          # cd $GITHUB_WORKSPACE
          # pip install -r data/scraper_job/requirements.txt
          # playwright install --with-deps
          touch data/scraper_job/requirements.txt
          echo "openai" >> data/scraper_job/requirements.txt

      - name: Set Variables
        run: |
          BRANCH="update-data-$(date +%Y%m%d%H%M%S)"
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=$OPENAI_API_KEY_DATA_UPDATE" >> $GITHUB_ENV

      - name: Run data update script
        run: |
          cd data/scraper_job
          python3 -u -m main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update data"
          branch: ${{ env.BRANCH_NAME }}
          base: main
          title: "Automated data update"
          body: "This PR includes updated data generated automatically."
          reviewers: pratkpranav
