name: Update Data and Create PR

on:
  workflow_dispatch: # Allows you to manually trigger the workflow
  schedule:
    - cron: "0 12 * * 1" # Run every Monday at 12:00 UTC
  push:
    branches:
      - automate-download

jobs:
  update-data:
    runs-on: ubuntu-latest-8-cores

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "pratik@thirdai.com"

      - name: Run data update script
        run: |

      - name: Check for changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "CHANGES_DETECTED=true" >> $GITHUB_ENV
          else
            echo "CHANGES_DETECTED=false" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.CHANGES_DETECTED == 'true'
        run: |
          BRANCH="update-data-$(date +%Y%m%d%H%M%S)"
          git checkout -b $BRANCH
          git add .
          git commit -m "Update data on $(date)"
          git push origin $BRANCH
          echo "BRANCH_NAME=$BRANCH" >> $GITHUB_ENV

      - name: Create Pull Request
        if: env.CHANGES_DETECTED == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update data"
          branch: ${{ env.BRANCH_NAME }}
          title: "Automated data update"
          body: "This PR includes updated data generated automatically."
          reviewers: your-username, ashutosh # Replace 'your-username' with your actual GitHub handle
